import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { BookOpen, ChevronRight, ExternalLink, PlayCircle, X } from 'lucide-react';
import api from '../services/api';

const phases = [
  ['Phase 1', 'Foundations of personal finance & markets', [
    ['Personal Finance & Wealth Building', ['Time value of money and compounding', 'Inflation and purchasing power', 'Emergency funds, debt management and goals'], 'Money Basics', 'https://zerodha.com/varsity/chapter/personal-finance-math-part-2/'],
    ['Macroeconomics & Stock Market Basics', ['Stocks, IPOs and public companies', 'NSE, BSE and SEBI', 'Demat accounts, trading accounts, CDSL and NSDL'], 'Stocks', 'https://zerodha.com/varsity/module/introduction-to-stock-markets/'],
  ]],
  ['Phase 2', 'Mutual funds & systematic investment plans', [
    ['Mutual Fund Fundamentals', ['AMC, trustee and custodian', 'Direct vs regular plans and expense ratios', 'Open-, close-ended and interval funds'], 'Mutual Funds', 'https://zerodha.com/varsity/chapter/mutual-fund-expense-ratio-direct-and-regular-plans/', 'https://www.youtube.com/embed/vElgDX5JF80'],
    ['Categories of Mutual Funds', ['Large-, mid-, small- and flexi-cap equity funds', 'Debt, hybrid and balanced funds', 'Index funds and ETFs'], 'Mutual Funds', 'https://zerodha.com/varsity/chapter/introduction-mutual-funds/'],
    ['SIPs & Portfolio Strategy', ['SIP and rupee-cost averaging', 'SWP and STP', 'Asset allocation, rebalancing and risk profiling'], 'Financial Planning', 'https://zerodha.com/varsity/chapter/asset-allocation-an-introduction/'],
  ]],
  ['Phase 3', 'Direct stock investing & market mechanics', [
    ['Order Types & Market Mechanics', ['Market, limit, stop-loss and bracket orders', 'Intraday trading vs delivery', 'Circuit limits, bull/bear markets, Nifty 50 and Sensex'], 'Stocks', 'https://zerodha.com/varsity/chapter/getting-started-2/'],
    ['Fundamental Analysis', ['Balance sheet, P&L and cash flow', 'P/E, P/B, ROE, ROCE, debt-to-equity and EPS', 'Management quality, moats and business models'], 'Markets', 'https://zerodha.com/varsity/module/fundamental-analysis/'],
  ]],
  ['Phase 4', 'Advanced concepts & risk management', [
    ['Technical Analysis & Charting', ['Candlestick patterns and support/resistance', 'SMA, EMA and volume analysis', 'Trendlines, RSI and MACD'], 'Technical Analysis', 'https://zerodha.com/varsity/module/technical-analysis/', 'https://www.youtube.com/embed/AYG2g3O7jKc'],
    ['Taxation & Portfolio Management', ['Short- and long-term capital gains', 'Dividend taxation and exit loads', 'Loss aversion and FOMO'], 'Tax Basics', 'https://zerodha.com/varsity/module/markets-and-taxation/'],
  ]],
];

const guides = {
  'Personal Finance & Wealth Building': { overview: 'Wealth building begins with cash flow, not stock selection. First make income, essential expenses, debt obligations, emergency savings and goals visible. Compounding works when money stays invested over time; inflation means the same amount of money generally buys less in the future.', learn: ['Separate needs, wants, obligations and goals before creating a budget.', 'Keep a cash reserve for genuine emergencies so you do not have to sell investments at a bad time.', 'Use a goal amount, target date and monthly contribution to turn intentions into a plan.', 'Compare investment returns with inflation to understand real purchasing-power growth.'], practice: 'Create one short-term goal and run a salary simulation with a lower income or unexpected expense.' },
  'Macroeconomics & Stock Market Basics': { overview: 'A company can raise capital by selling ownership shares through an IPO. After listing, investors transact with each other on an exchange; a broker connects the investor to the market, while depositories hold securities electronically. SEBI regulates India’s securities market.', learn: ['A stock is a claim on a business, not simply a moving price on a screen.', 'NSE and BSE facilitate trading; CDSL and NSDL are depositories; a DP provides access to a demat account.', 'IPO proceeds may fund growth, debt reduction or an exit by existing shareholders—read the offer document.', 'Indices such as Nifty 50 and Sensex are baskets used to track a section of the market.'], practice: 'Use the virtual lab to compare a broad index fund with one individual share.' },
  'Mutual Fund Fundamentals': { overview: 'A mutual fund pools investors’ money into a scheme with a stated objective. The AMC manages investments, trustees oversee investor interests and a custodian safekeeps assets. Your return depends on the underlying holdings and costs, not on a promise from the fund.', learn: ['NAV is the per-unit value of a scheme; it is not a signal that a fund is cheap or expensive.', 'The expense ratio is charged from scheme assets and affects long-term returns.', 'Direct and regular plans hold the same portfolio but can have different expenses because regular plans include distributor compensation.', 'Open-ended funds generally allow ongoing purchase/redemption; check product-specific rules for close-ended and interval funds.'], practice: 'Compare the expense ratios and stated mandates of two same-category fund factsheets.' },
  'Categories of Mutual Funds': { overview: 'Fund categories describe what a scheme is allowed to own. They do not remove risk. Equity funds can fluctuate sharply; debt funds have interest-rate, credit and liquidity risks; hybrid funds combine exposures; index funds seek to track an index; ETFs trade on an exchange.', learn: ['Large-, mid- and small-cap labels refer to company-size segments, not guaranteed safety or returns.', 'Flexi-cap funds can move across market-cap segments within their mandate.', 'Debt-fund risk includes duration sensitivity and issuer credit quality.', 'An ETF needs a demat account and has market price as well as tracking considerations.'], practice: 'Choose an asset type for a virtual goal based on a short, medium or long time horizon.' },
  'SIPs & Portfolio Strategy': { overview: 'A SIP is a scheduled way to invest, often into a mutual fund. It does not guarantee profit or protect capital. Asset allocation decides how money is spread across assets; rebalancing restores a chosen risk mix when market movements change it.', learn: ['Rupee-cost averaging means a fixed contribution buys more or fewer units as price changes.', 'An STP transfers money between schemes; an SWP withdraws periodically—both have product and tax implications.', 'Risk capacity depends on emergency reserves, debt, income stability and time horizon, not only personality.', 'Rebalance to a planned allocation rather than chasing the asset class that recently performed best.'], practice: 'Use the SIP calculator, then compare the outcome when duration changes versus when the assumed return changes.' },
  'Order Types & Market Mechanics': { overview: 'An order tells the broker how to attempt a trade. A market order prioritises execution, while a limit order specifies a price condition. Stop-loss orders are risk-management tools but can execute differently in fast markets. Delivery and intraday positions have different risk and operational characteristics.', learn: ['Read order type, quantity, price, validity and estimated charges before confirming.', 'A circuit limit pauses or restricts trading when a security moves sharply.', 'Bull and bear market labels describe broad direction, not a timing signal.', 'Nifty 50 and Sensex are benchmarks; owning an index product differs from simply watching an index.'], practice: 'In the virtual lab, compare a market and limit order without risking real money.' },
  'Fundamental Analysis': { overview: 'Fundamental analysis studies the economics of a business and the price paid for its shares. It combines financial statements with qualitative research. A ratio is a question starter, not a verdict.', learn: ['Income statement: revenue, expenses and profit over a period.', 'Balance sheet: assets, liabilities and shareholder equity at a point in time.', 'Cash-flow statement: operating, investing and financing cash movements.', 'P/E, P/B, ROE, ROCE, EPS and debt-to-equity must be interpreted against the business, peers and history.'], practice: 'Pick a simulated company and write three questions about its business model, debt and cash generation.' },
  'Technical Analysis & Charting': { overview: 'Technical analysis studies historical price and volume data. A candle records open, high, low and close for a chosen timeframe. Patterns and indicators can help organise observations, but they cannot eliminate uncertainty or replace position sizing and risk controls.', learn: ['Support and resistance are zones where price previously found buying or selling interest.', 'SMA gives equal weight to observations; EMA weights recent observations more heavily.', 'Volume can help contextualise a price move but does not confirm a future outcome.', 'RSI and MACD are derived indicators that can give false or late signals, especially in range-bound markets.'], practice: 'Use a demo chart to identify OHLC values and write what would invalidate a hypothetical view.' },
  'Taxation & Portfolio Management': { overview: 'Investment taxation depends on the asset, holding period, transaction type and current law. Keep records rather than relying on memory. Behaviour also matters: fear, FOMO and loss aversion can lead to decisions that do not match a written plan.', learn: ['Short- and long-term capital-gains treatment varies by asset and law; verify current rules before filing.', 'Dividends and exit loads can affect the cash you receive and the return you keep.', 'Record purchase date, price, sale date, charges and statements.', 'Use a written rule for rebalancing and avoid reacting to social-media hype or a single day of market movement.'], practice: 'Review a sample investment statement and list the records you would retain for tax review.' },
};

const Learn = () => {
  const [courses, setCourses] = useState([]);
  const [loading, setLoading] = useState(true);
  const [active, setActive] = useState(phases[0][2][0]);
  const [detailOpen, setDetailOpen] = useState(false);

  useEffect(() => {
    api.get('/learning/courses').then(response => setCourses(response.data)).catch(error => console.error('Unable to load learning catalogue', error)).finally(() => setLoading(false));
  }, []);

  const matchingCourse = useMemo(() => courses.find(course => course.category === active[2]), [courses, active]);

  if (loading) return <div className="grid min-h-screen place-items-center bg-brand-bg text-sm text-brand-muted">Loading your learning path…</div>;

  return <div className="page-shell px-5 py-8 md:px-8 lg:px-12 lg:py-10"><div className="mx-auto max-w-7xl">
    <header className="max-w-3xl"><p className="eyebrow">FinAura Academy</p><h1 className="mt-2 font-serif text-4xl text-brand-ink md:text-5xl">Learn finance in a clear order.</h1><p className="mt-4 text-sm leading-7 text-brand-muted">Start with money fundamentals, then build toward funds, stocks, analysis and portfolio management. Each FinAura module combines plain-language study, practice and quizzes with verified Zerodha Varsity source material.</p></header>
    <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]">
      <section className="space-y-5">{phases.map(([phase, title, modules]) => <div key={phase} className="surface-card overflow-hidden"><div className="border-b border-brand-border px-5 py-4 md:px-6"><p className="eyebrow">{phase}</p><h2 className="mt-1 text-lg font-semibold text-brand-ink">{title}</h2></div><div className="divide-y divide-brand-border">{modules.map(module => { const isActive = active[0] === module[0]; return <button key={module[0]} type="button" onClick={() => { setActive(module); setDetailOpen(true); }} className={`flex w-full items-start gap-4 px-5 py-5 text-left transition md:px-6 ${isActive ? 'bg-brand-light' : 'hover:bg-brand-bg'}`}><span className={`mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-full text-xs font-bold ${isActive ? 'bg-brand-primary text-white' : 'bg-brand-light text-brand-primary'}`}>{modules.indexOf(module) + 1}</span><span className="min-w-0 flex-1"><span className="block font-semibold text-brand-ink">{module[0]}</span><span className="mt-2 grid gap-1 text-xs leading-5 text-brand-muted sm:grid-cols-2">{module[1].map(topic => <span key={topic}>• {topic}</span>)}</span><span className="mt-3 inline-flex text-xs font-bold text-brand-primary">Open complete module guide</span></span><ChevronRight size={18} className="mt-1 shrink-0 text-brand-sage" /></button>; })}</div></div>)}</section>
      <aside className="surface-card h-fit p-5 lg:sticky lg:top-6"><div className="flex items-center gap-2 text-brand-primary"><PlayCircle size={18} /><span className="text-xs font-bold uppercase tracking-wider">Module study room</span></div><h2 className="mt-3 text-xl font-semibold text-brand-ink">{active[0]}</h2><p className="mt-2 text-sm leading-6 text-brand-muted">{active[1].join(' · ')}</p>{active[4] ? <div className="mt-5 aspect-video overflow-hidden rounded-xl bg-brand-light"><iframe className="h-full w-full" src={active[4]} title={`${active[0]} video`} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div> : <div className="mt-5 rounded-xl bg-brand-light p-4 text-sm leading-6 text-brand-muted">Use the verified Varsity reading below. An embedded video is added only when it directly matches this module.</div>}<a className="mt-5 inline-flex items-center gap-2 rounded-xl border border-brand-primary px-3 py-2.5 text-sm font-semibold text-brand-primary" href={active[3]} target="_blank" rel="noreferrer">Read on Zerodha Varsity <ExternalLink size={15} /></a>{matchingCourse && <Link to={`/learn/course/${matchingCourse._id}`} className="mt-3 flex items-center gap-2 text-sm font-semibold text-brand-primary">Practice in FinAura <ChevronRight size={15} /></Link>}<p className="mt-5 border-t border-brand-border pt-4 text-xs leading-5 text-brand-muted">Zerodha Varsity links are source material. FinAura’s quizzes and simulations are educational—not investment advice.</p></aside>
    </div>
    <section className="mt-10"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Practice catalogue</p><h2 className="mt-1 text-2xl font-semibold text-brand-ink">FinAura lessons & quizzes</h2></div><span className="text-sm text-brand-muted">{courses.length} courses</span></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{courses.map(course => <article key={course._id} className="surface-card flex flex-col p-5"><div className="flex justify-between gap-3"><span className="text-[10px] font-bold uppercase tracking-wider text-brand-primary">{course.category}</span><span className="text-xs text-brand-muted">{course.progress.totalLessons} lessons</span></div><h3 className="mt-3 font-semibold text-brand-ink">{course.title}</h3><p className="mt-2 flex-1 text-sm leading-6 text-brand-muted">{course.description}</p><div className="mt-5"><div className="mb-2 flex justify-between text-xs text-brand-muted"><span>{course.progress.completedLessons} completed</span><span>{course.progress.percentComplete}%</span></div><div className="h-1.5 rounded-full bg-brand-light"><div className="h-full rounded-full bg-brand-primary" style={{ width: `${course.progress.percentComplete}%` }} /></div></div><Link to={`/learn/course/${course._id}`} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-brand-primary">Open FinAura course <ChevronRight size={15} /></Link></article>)}</div></section>
    {detailOpen && <div className="fixed inset-0 z-50 overflow-y-auto bg-brand-ink/35 p-4 backdrop-blur-sm"><div className="mx-auto my-8 max-w-3xl rounded-2xl bg-white p-6 shadow-xl md:p-8"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Complete module guide</p><h2 className="mt-2 text-3xl font-semibold text-brand-ink">{active[0]}</h2></div><button onClick={() => setDetailOpen(false)} className="rounded-lg p-2 text-brand-muted hover:bg-brand-light" aria-label="Close module guide"><X size={20} /></button></div><p className="mt-5 text-base leading-7 text-brand-muted">{guides[active[0]]?.overview}</p><div className="mt-7 rounded-xl bg-brand-light p-5"><h3 className="font-semibold text-brand-ink">What you will understand</h3><ul className="mt-3 space-y-3 text-sm leading-6 text-brand-muted">{guides[active[0]]?.learn.map(item => <li key={item} className="flex gap-2"><span className="font-bold text-brand-primary">✓</span>{item}</li>)}</ul></div><div className="mt-5 rounded-xl border border-brand-border p-5"><p className="eyebrow">Try it safely</p><p className="mt-2 text-sm leading-6 text-brand-muted">{guides[active[0]]?.practice}</p></div>{active[4] && <div className="mt-5 aspect-video overflow-hidden rounded-xl"><iframe className="h-full w-full" src={active[4]} title={`${active[0]} video`} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div>}<div className="mt-7 flex flex-wrap gap-3"><a href={active[3]} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-brand-primary px-4 py-2.5 text-sm font-semibold text-brand-primary">Read verified Varsity material <ExternalLink size={15} /></a>{matchingCourse && <Link to={`/learn/course/${matchingCourse._id}`} className="inline-flex items-center gap-2 rounded-xl bg-brand-primary px-4 py-2.5 text-sm font-semibold text-white">Practice with quizzes <ChevronRight size={15} /></Link>}</div></div></div>}
  </div></div>;
};

export default Learn;
